---
    language: java
    sudo: false
    jdk:
        - oraclejdk8

    before_cache:
        - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
    cache:
        directories:
            - $HOME/.gradle/caches/
            - $HOME/.gradle/wrapper/

    branches:
        only:
            - master
            - "/^[0-9]+\\.[0-9]+\\.[0-9]+/"

    before_install: pip install --user codecov
    script: ./gradlew clean build
    after_success: codecov
